version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cache-engine"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/cache-engine/web"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
