apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../secret.example.yaml
  - ../../backend-pvc.yaml
  - ../../backend-deployment.yaml
  - ../../backend-service.yaml
  - ../../frontend-deployment.yaml
  - ../../frontend-service.yaml
  - ../../ingress.yaml

images:
  - name: ghcr.io/your-org/cache-engine-api:latest
    newName: cache-engine-api
    newTag: kind
  - name: ghcr.io/your-org/cache-engine-web:latest
    newName: cache-engine-web
    newTag: kind

patches:
  - path: configmap.patch.yaml
  - path: secret.patch.yaml
  - path: ingress.patch.yaml
